// layout
export const SET_THEME = "SET_THEME"
export const SET_POPUP = "SET_POPUP"
export const SET_PERS_DRAWER = "SET_PERS_DRAWER"
export const SET_TEMP_DRAWER = "SET_TEMP_DRAWER"

// timer
export const SET_DURATION = "SET_DURATION"
export const RESET_TIMER = "RESET_TIMER"
export const SET_TIME = "SET_TIME"
export const SET_STATUS = "SET_STATUS"
export const SET_TIMER_UPDATE_INTERVAL = "SET_TIMER_UPDATE_INTERVAL"
export const SET_TIMER_STOP_TIMEOUT = "SET_TIMER_STOP_TIMEOUT"
export const UPDATE_RUNNING_DATA = "UPDATE_RUNNING_DATA"
export const SET_ANIMATION_ID = "SET_ANIMATION_ID"

// settings
export const SET_WORK_SESSION_DURATION = "SET_WORK_SESSION_DURATION"
export const SET_SHORT_BREAK_DURATION = "SET_SHORT_BREAK_DURATION"
export const SET_LONG_BREAK_DURATION = "SET_LONG_BREAK_DURATION"
export const SET_WORK_SESSIONS_COUNT_BEFORE_LONG_BREAK =
  "SET_WORK_SESSIONS_COUNT_BEFORE_LONG_BREAK"

// sessions
export const SET_CONFIGURATION = "SET_CONFIGURATION"
export const SET_CURRENT_SESSION = "SET_CURRENT_SESSION"
export const SET_SESSION_LOOP = "SET_SESSION_LOOP"

// tasks
export const ADD_TASK = "ADD_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const EDIT_TASK = "EDIT_TASK"
export const SET_TASKS = "SET_TASKS"
export const SELECT_TASK = "SELECT_TASK"
